grafana:
  adminUser: admin
  adminPassword: admin
  service:
    type: ClusterIP

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 10d

alertmanager:
  enabled: true
