# k8s/secrets/cluster-secret-store.yaml
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-store
spec:
  provider:
    # אנחנו אומרים ל-ESO שהספק שלנו הוא AWS
    aws:
      service: SecretsManager
      # האזור שבו נמצא הקלאסטר והסודות שלנו (ראינו בטרהפורם שזה us-east-1)
      region: us-east-1
      # מנגנון ההזדהות: אנחנו משתמשים ב-IRSA (IAM Role for Service Accounts)
      # כלומר, ה-ESO משתמש בזהות של הפוד של עצמו כדי להוכיח ל-AWS מי הוא
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets # השם הדיפולטיבי של ה-ServiceAccount של ESO
            namespace: external-secrets