# k8s/secrets/external-secrets.yaml

# ==========================================
# בקשת עבודה מספר 1: משיכת הסיסמה של Postgres
# ==========================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-external-secret
  namespace: default # המקום שבו תרוץ האפליקציה (אם יצרתם namespace אחר, תשנה כאן)
spec:
  refreshInterval: "1h" # כל כמה זמן לבדוק מול AWS אם הסיסמה השתנתה

  secretStoreRef:
    name: aws-secrets-store # חיבור ל"שגריר" שיצרנו בקובץ הקודם
    kind: ClusterSecretStore

  target:
    name: my-pg-secret # השם המדויק שהשותפה ביקשה ליצור בקוברנטיס!
    creationPolicy: Owner

  data:
    # איך לבנות את הסוד המקומי בקוברנטיס:
    - secretKey: postgres-password # השם של המפתח שפוסטגרס של Bitnami מצפה למצוא (ברירת המחדל שלהם)
      remoteRef:
        key: statuspage-yarin-noa-secrets-yU5rQG # שם הסוד הראשי ב-AWS Secrets Manager
        property: POSTGRES_PASSWORD # השם של השדה הספציפי בתוך ה-JSON של AWS (תצטרך לוודא שזה השם שטרהפורם ייצר, לפעמים זה באותיות קטנות)

---
# ==========================================
# בקשת עבודה מספר 2: משיכת הסיסמה של Redis
# ==========================================
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-external-secret
  namespace: default
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: my-redis-secret # השם המדויק שהשותפה ביקשה ליצור עבור רדיס!
    creationPolicy: Owner
  data:
    - secretKey: redis-password # המפתח שרדיס מצפה לו
      remoteRef:
        key: statuspage-yarin-noa-secrets-yU5rQG # אותו סוד ראשי ב-AWS
        property: REDIS_PASSWORD # השדה הספציפי של רדיס בתוך ה-JSON ב-AWS