apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: statuspage-secrets-sync
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: statuspage-app-secrets # איחדנו לסוד אחד מרכזי
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: statuspage-yarin-noa-secrets
        property: POSTGRES_PASSWORD
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: statuspage-yarin-noa-secrets
        property: REDIS_PASSWORD
    - secretKey: DEBUG
      remoteRef:
        key: statuspage-yarin-noa-secrets
        property: DEBUG
    - secretKey: SECRET_KEY
      remoteRef:
        key: statuspage-yarin-noa-secrets
        property: SECRET_KEY