# הגדרת גרסת ה-API הייעודית של מערכת ArgoCD
apiVersion: argoproj.io/v1alpha1
# סוג המשאב שאנחנו מייצרים (אפליקציה ש-ArgoCD מנהל)
kind: Application
metadata:
  # השם של האפליקציה כפי שיופיע בממשק של ArgoCD
  name: status-page
  # מרחב השמות שבו ייווצר *המשאב הזה* (תמיד חייב להיות בתוך argocd כדי שהמערכת תזהה אותו)
  namespace: argocd
spec:
  # שיוך לפרויקט פנימי ב-ArgoCD (פרויקט default קיים מראש ומתאים לנו)
  project: default

  # --- מאיפה לוקחים את הקוד? (Source) ---
  source:
    # הכתובת של מאגר הגיטהב שלך (חייב להסתיים ב- .git)
    repoURL: https://github.com/yarinalma6/nitzanim-final-workshop.git
    # הענף (Branch) בגיט שאחריו ArgoCD צריך לעקוב
    targetRevision: main
    # התיקייה הספציפית בתוך הריפו שבה נמצאים קבצי הקוברנטיס (Deployment, Services)
    path: k8s

  # --- לאן מתקינים את הקוד? (Destination) ---
  destination:
    # הכתובת הפנימית של הקלאסטר שבו ArgoCD רץ (מתקין על עצמו)
    server: https://kubernetes.default.svc
    # מרחב השמות (Namespace) שאליו תותקן האפליקציה שלך
    namespace: statuspage

  # --- איך לבצע את הסנכרון? (Sync Policy) ---
  syncPolicy:
    # הגדרת סנכרון אוטומטי (ללא צורך בלחיצת כפתור אנושית)
    automated:
      # אם קובץ נמחק מהגיט, ArgoCD ימחק את המשאב מהקלאסטר (מונע "הצטברות זבל")
      prune: true
      # אם מישהו משנה משהו ידנית בקלאסטר, ArgoCD ידרוס אותו מיד ויחזיר למצב שכתוב בגיט
      selfHeal: true
    # אפשרויות סנכרון נוספות
    syncOptions:
      # אם ה-Namespace שהגדרנו (status-page) לא קיים, ArgoCD ייצור אותו אוטומטית לפני ההתקנה
      - CreateNamespace=true