# ==============================================================================
# תצורת פריסה (Deployment) - חזרה לגרסה היציבה
# ==============================================================================

apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statuspage
  template:
    metadata:
      labels:
        app: statuspage
    spec:
      initContainers:
        - name: run-migrations
          image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yarin-noa-project:2d6e6dc7ee7b2b3c0868fab5c0bc45e460afc7ee
          imagePullPolicy: Always
          workingDir: /app/statuspage
          command: ["/bin/sh", "-c"]
          args:
            - |
              python -m pip install --target . rq-scheduler --no-cache-dir
              python manage.py migrate --noinput
          env:
            - name: DB_HOST
              value: "statuspage-postgres-postgresql.default.svc.cluster.local"
            - name: DB_NAME
              value: "statuspage"
            - name: DB_USER
              value: "postgres"
            - name: REDIS_HOST
              value: "statuspage-redis-master.default.svc.cluster.local"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: statuspage-app-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: statuspage-app-secrets
                  key: DB_PASSWORD
          envFrom:
            - secretRef:
                name: statuspage-app-secrets

      containers:
      - name: statuspage-container
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yarin-noa-project:2d6e6dc7ee7b2b3c0868fab5c0bc45e460afc7ee
        imagePullPolicy: Always
        workingDir: /app/statuspage
        ports:
          - containerPort: 8000
        command: ["/bin/sh", "-c"]
        args:
          - |
            python -m pip install --target . rq-scheduler --no-cache-dir
            gunicorn --bind 0.0.0.0:8000 statuspage.wsgi:application
        env:
          - name: DB_HOST
            value: "statuspage-postgres-postgresql.default.svc.cluster.local"
          - name: DB_NAME
            value: "statuspage"
          - name: DB_USER
            value: "postgres"
          - name: REDIS_HOST
            value: "statuspage-redis-master.default.svc.cluster.local"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: statuspage-app-secrets
                key: DB_PASSWORD
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: statuspage-app-secrets
                key: DB_PASSWORD
        envFrom:
          - secretRef:
              name: statuspage-app-secrets