apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page
spec:
  replicas: 2
  selector:
    matchLabels:
      app: statuspage
  template:
    metadata:
      labels:
        app: statuspage
    spec:
      # --- שלב המיגרציות ---
      initContainers:
      - name: run-migrations
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yarin-noa-project:latest
        command: ["python", "statuspage/manage.py", "migrate", "--noinput"]
        env:
          - name: DB_HOST
            value: "statuspage-postgres-postgresql"
          - name: DB_NAME
            value: "statuspage"
          - name: DB_USER
            value: "postgres"
        envFrom:
          - secretRef:
              name: statuspage-app-secrets

      # --- האפליקציה הראשי ---
      containers:
      - name: statuspage-container
        image: 992382545251.dkr.ecr.us-east-1.amazonaws.com/yarin-noa-project:latest
        ports:
          - containerPort: 8000
        env:
          - name: DB_HOST
            value: "statuspage-postgres-postgresql"
          - name: DB_NAME
            value: "statuspage"
          - name: DB_USER
            value: "postgres"
          - name: REDIS_URL
            value: "redis://statuspage-redis-master:6379"
        envFrom:
          - secretRef:
              name: statuspage-app-secrets