apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: status-page-ingress
  namespace: statuspage
  annotations:
    # אומר ל-AWS: "תיצור ALB שחשוף לאינטרנט"
    alb.ingress.kubernetes.io/scheme: internet-facing
    # אומר ל-AWS: "תעביר תנועה ישירות ל-IP של הפודים"
    alb.ingress.kubernetes.io/target-type: ip
    # --- תוספות עבור HTTPS ---
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:992382545251:certificate/7cfd330a-ae94-4daa-a5d0-8f1f27145e04
    alb.ingress.kubernetes.io/ssl-redirect: '443'

    # --- הגדרות Health Check עבור ה-ALB ב-AWS ---
    # אנו מוודאים שה-ALB בודק בדיוק את מה שהפוד בודק
    alb.ingress.kubernetes.io/healthcheck-path: /dashboard/login/
    alb.ingress.kubernetes.io/healthcheck-port: '8000'
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: "200-399"
    # --------------------------------------------
spec:
  ingressClassName: alb
  rules:
  - host: status.yarin-noa.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: status-page-service
            port:
              number: 80